{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/type: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/type: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/type: frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullsecretname }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              name: http
          
          env:
            - name: BACKEND_HOST
              value: "{{ .Values.frontend.env.backendHost }}"
            - name: BACKEND_PORT
              value: "{{ .Values.frontend.env.backendPort }}"

{{- if .Values.frontend.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
{{- end }}

          resources:
            requests:
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
              memory: "{{ .Values.frontend.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
              memory: "{{ .Values.frontend.resources.limits.memory }}"
{{- end }}