# Generated by Django 5.2.12 on 2026-06-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_contacto_urg_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensagem de erro ou aviso sobre a pipeline da IA.')),
                ('is_read', models.BooleanField(default=False, help_text='Indica se o utilizador já leu a notificação.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Notificação do Sistema',
                'verbose_name_plural': 'Notificações do Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
