# Generated by Django 5.2.12 on 2026-05-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0004_delete_extractedsections'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('EXTRACTION', 'Extração de Diário'), ('SUMMARIZATION', 'Geração de Sumário')], max_length=20)),
                ('duration_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diaries.clinicaldiary')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
