# Generated by Django 5.2.12 on 2026-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='inference_duration',
            field=models.FloatField(default=0, help_text='Tempo real de processamento do modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='input_size',
            field=models.IntegerField(default=0, help_text='Número de caracteres ou tokens processados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='is_retry',
            field=models.BooleanField(default=False, help_text='Se houve falhas antes do sucesso'),
        ),
    ]
