# Generated by Django 5.2.12 on 2026-06-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_performancemetric_inference_duration_and_more'),
        ('patients', '0002_patient_contacto_urg_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetric',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='fallback_used',
            field=models.BooleanField(default=False, help_text='Se falhou as 3x e aplicou dados parciais/erros'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='section_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='tokens_per_second',
            field=models.FloatField(blank=True, help_text='Velocidade de geração da LLM', null=True),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='duration_seconds',
            field=models.FloatField(help_text='Tempo total da operação (inclui código Python + LLM)'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='inference_duration',
            field=models.FloatField(default=0.0, help_text='Tempo exclusivo de inferência da LLM'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='input_size',
            field=models.IntegerField(help_text='Número de caracteres processados (Input)'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='is_retry',
            field=models.BooleanField(default=False, help_text='Se a LLM falhou a 1ª tentativa e precisou de retry'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='operation_type',
            field=models.CharField(choices=[('OCR_PAGE', 'OCR de Página PDF (Tesseract)'), ('PRE_CLEAN_CHUNK', 'Limpeza Prévia LLM (Bloco PDF)'), ('EXTRACTION', 'Extração de Diário'), ('SUMM_SECTION', 'Sumarização por Secção (LLM)'), ('SUMMARIZATION_TOTAL', 'Geração de Sumário Global'), ('TRIAGE_ANALYSIS', 'Análise de Triagem')], max_length=25),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='patients.patient'),
        ),
    ]
