# Generated by Django 5.2.12 on 2026-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_performancemetric_model_ram_gb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancemetric',
            name='model_ram_gb',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='model_vram_gb',
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='attempt_count',
            field=models.IntegerField(blank=True, help_text='Número de tentativas até obter uma resposta válida (1 a 3)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='Tokens reais gerados na resposta', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='error_type',
            field=models.CharField(blank=True, help_text="Categoria do erro quando fallback_used=True: 'invalid_json', 'missing_key', 'network', 'timeout'", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='finish_reason',
            field=models.CharField(blank=True, help_text="'stop' (terminou naturalmente) ou 'length' (cortado pelo limite de tokens)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='kv_cache_usage_percent',
            field=models.FloatField(blank=True, help_text='Fração do KV cache ocupada no momento da chamada (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='Tokens reais de entrada, devolvidos pelo servidor', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='requests_waiting',
            field=models.IntegerField(blank=True, help_text='Pedidos em fila de espera no servidor no momento da chamada', null=True),
        ),
    ]
