# Generated by Django 5.2.12 on 2026-07-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_performancemetric_model_ram_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='model_ram_gb',
            field=models.FloatField(blank=True, help_text='RAM ocupada pelo modelo no momento da chamada', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='model_vram_gb',
            field=models.FloatField(blank=True, help_text='VRAM ocupada pelo modelo no momento da chamada', null=True),
        ),
    ]
