# Generated by Django 5.2.12 on 2026-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_performancemetric_model_ram_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetric',
            name='operation_type',
            field=models.CharField(choices=[('NATIVE_TEXT_PAGE', 'Extração Automática de Texto (PDF)'), ('OCR_PAGE', 'OCR de Página PDF (Tesseract)'), ('PRE_CLEAN_CHUNK', 'Limpeza Prévia LLM (Bloco PDF)'), ('EXTRACTION', 'Extração de Diário'), ('SUMM_SECTION', 'Sumarização por Secção (LLM)'), ('SUMMARIZATION_TOTAL', 'Geração de Sumário Global'), ('TRIAGE_ANALYSIS', 'Análise de Triagem')], max_length=25),
        ),
    ]
