namespace: teses-26
pullsecretname: regcred
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: git.ulscoimbra.min-saude.pt/teses26/clinical-ai-system-backend
    tag: v0.0.1
    pullPolicy: IfNotPresent
  containerPort: 8000
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
  env:
    DATABASE_NAME: "clinical-ai"
    DATABASE_HOST: "pg-testes-pooler.teses-26.svc.cluster.local"
    DATABASE_PORT: "5432"
    FRONTEND_URL: "http://172.19.2.222:31405"
  secretName: clinical-ai-system-secret
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  probes:
    enabled: false
    startup:
      path: /api/health/
      initialDelaySeconds: 0
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 30
    readiness:
      path: /api/health/
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    liveness:
      path: /api/health/
      initialDelaySeconds: 0
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: git.ulscoimbra.min-saude.pt/teses26/clinical-ai-system-frontend
    tag: v0.0.1
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 31405
  env:
    backendHost: "clinical-ai-backend.teses-26.svc.cluster.local"
    backendPort: "8000"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "250m"
      memory: "128Mi"
  probes:
    enabled: true
    readiness:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    liveness:
      path: /
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 3
      failureThreshold: 3
