# Generated by Django 5.2.12 on 2026-04-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_number', models.IntegerField(blank=True, null=True)),
                ('original_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'diary_number'],
                'unique_together': {('patient', 'diary_number')},
            },
        ),
        migrations.CreateModel(
            name='ExtractedSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='diaries.clinicaldiary')),
            ],
        ),
    ]
