# Generated by Django 5.2.12 on 2026-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldiary',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
