# Generated by Django 5.2.12 on 2026-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_alter_clinicaldiary_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldiary',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
