# Generated by Django 5.2.12 on 2026-04-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_clinicaldiary_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedSections',
        ),
    ]
