# Generated by Django 5.2.12 on 2026-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_delete_extractedsections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldiary',
            name='cleaned_text',
        ),
        migrations.AddField(
            model_name='clinicaldiary',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
